doctrine :
  dbal :
    url : '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm :
    auto_generate_proxy_classes : true
    naming_strategy : doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping : true
    filters :
      deleted_entity :
        class : App\ORM\DeletedEntityFilter
    mappings :
      App :
        is_bundle : false
        type : attribute
        dir : '%kernel.project_dir%/src/Entity'
        prefix : 'App\Entity'
        alias : App
    dql:
      datetime_functions:
        timestampdiff: App\ORM\TimestampDiff
        month: App\ORM\Month
        year: App\ORM\Year
      string_functions :
        JSON_CONTAINS : Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
