parameters:
  sammy:
    single.instance: 0
    license.name: Codific SAMMY
    login:
      register: 1
      internal: 1
      github: 1
      gitlab: 1
      sso: 0
      admin: 1
      vpn: 0

    raw.answers.export: 1
    myScopes: 0