name: Symfony

on:
  push:
    branches:
      - 'ph-codific/i18n-FR:trans_2'
  workflow_dispatch:

permissions:
  contents: read

initial_setup:
  run:
    steps:
      #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      # uses: shivammathur/setup-php@v2
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

jobs:
  clone-owasp-samm:
    runs-on: ubuntu-latest
    steps:
      - name: Run intial steps setup
        - extends: initial_setup.run.steps
      - name: Clone Owasp SAMM
        run: sh scripts/clone_owasp_samm.sh

  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Run intial steps setup
      - extends: initial_setup.run.steps
    - name: Create Database
      run: sh scripts/generate_pdf.sh
    - uses: actions/upload-artifact@v3
      with:
        name: samm.pdf
        path: export/SAMM.pdf
